chore: disable tf plan from pipeline

diff --git a/.github/workflows/iac.yml b/.github/workflows/iac.yml
--- a/.github/workflows/iac.yml
+++ b/.github/workflows/iac.yml
@@ -40,18 +40,18 @@ jobs:
           role-to-assume: ${{ secrets.AWS_ROLE }}
           aws-region: ${{ secrets.AWS_REGION }}
 
-      - name: Set up Terraform
-        uses: hashicorp/setup-terraform@v3
+      # - name: Set up Terraform
+      #   uses: hashicorp/setup-terraform@v3
         
-      - name: Initialize Terraform
-        working-directory: ./tf
-        run: terraform init -ignore-remote-version
+      # - name: Initialize Terraform
+      #   working-directory: ./tf
+      #   run: terraform init -ignore-remote-version
         
-      - name: Plan Terraform
-        working-directory: ./tf
-        run: |
-          terraform plan -refresh=false -out="tfplan.bin"
-          terraform show -json "tfplan.bin" | jq  > "../.github/tfplan.json"
+      # - name: Plan Terraform
+      #   working-directory: ./tf
+      #   run: |
+      #     terraform plan -refresh=false -out="tfplan.bin"
+      #     terraform show -json "tfplan.bin" | jq  > "../.github/tfplan.json"
     
       - name: Run Checkov
         id: checkov
@@ -67,10 +67,10 @@ jobs:
         with:
           sarif_file: results.sarif
 
-      - name: Commit Terraform plan
-        id: commit 
-        uses: stefanzweifel/git-auto-commit-action@v5
-        if: success() || failure()
-        with:
-          commit_message: "IaC Template [no ci]"
-          file_pattern: ".github/tfplan.*"
+      # - name: Commit Terraform plan
+      #   id: commit 
+      #   uses: stefanzweifel/git-auto-commit-action@v5
+      #   if: success() || failure()
+      #   with:
+      #     commit_message: "IaC Template [no ci]"
+      #     file_pattern: ".github/tfplan.*"
